import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import NavBar from "@/components/navBar";
import { Footer } from "@/components/footer";

export const metadata: Metadata = {
  title: "Concrete Delivery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <NavBar />
          {children}
          <div className="pt-10">
            <Footer />
          </div>
        </ChakraProvider>
      </body>
    </html>
  );
}
